#!/bin/bash

[ "$(id -u)" == "0" ] || { echo "You must be root" ; exit 1; }

set -e

freshclam

nice -n 20 clamscan --recursive --infected \
  /boot \
  /etc \
  /home \
  /nix \
  /opt \
  /root \
  /usr \
  /var
