#!/usr/bin/env ruby


REGEX = /([a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.(com|org|net))/

STDIN.lines.each do |line|
  domains = line.to_enum(:scan, REGEX).map { Regexp.last_match }
  if (! domains.empty?) then
    puts domains[0]
  end
end
