#!/bin/bash

threshold=$(date -d "2 years ago" +%s)

all_branches=$(git branch --list --remote | grep -v origin/HEAD)

for branch in $all_branches; do
  last_commit_timestamp=$(git log -n 1 --format="%at" $branch)
  last_commit_timestamp_human=$(git log -n 1 --format="%ai" $branch)

  if [ "$last_commit_timestamp" -lt "$threshold" ]; then
    echo "$last_commit_timestamp_human: $branch"
  fi
done
