#!/bin/bash

X='-r'
if [ "$(uname -s)" == "Darwin" ]; then
  X=
fi

DEF_BRANCH=$(git-default-branch)

git branch --list --merged "origin/$DEF_BRANCH" | \
  egrep -v '^\*' | \
  egrep -v '^\s*'"$DEF_BRANCH"'$' | \
  xargs $X -n 1 git branch -d
