#!/bin/sh
#
# Used by emacs' haskell layer
#


if [ -z "$NIX_STORE" ] ; then
  USE_NIX=
else
  USE_NIX=--nix
fi

exec nice -n 20 \
     stack build \
     $USE_NIX \
     --fast \
     --test \
     --bench \
     --no-run-tests \
     --no-run-benchmarks \
     --ghc-options=-ferror-spans \
     2>&1 | sed -e 's/^[a-zA-Z-]* *> //'
