#!/usr/bin/env ruby

def printusageandexit(exitcode)
	puts <<"__E__"
Usage: #{$0} [--nargs N] cmdline
__E__
	exit exitcode
end

def runsyscmd(args)
	system(*args)
end

opt_nargs = 1024

while true do
	break unless ARGV.size > 0

	opt = ARGV.shift
	case opt
		when '-h', '--help'  then printusageandexit 0
		when '-n', '--nargs' then
			if ARGV.size == 0
				printusageandexit 1
			else
				opt_nargs = ARGV.shift.to_i
			end
	else
		ARGV.unshift opt
		break
	end
end


if ARGV.size > 0
	cmdline = ARGV
else
	cmdline = Array.new
	cmdline.push 'echo'
end

curcmd = cmdline.clone

$stdin.each { |line|
	curcmd.push line.chomp

	if (curcmd.size - cmdline.size) % opt_nargs == 0
		runsyscmd curcmd
		curcmd = cmdline.clone
	end
}

# leftover
if curcmd.size > cmdline.size
	runsyscmd curcmd
end
