#!/usr/bin/ruby

#
# stupid hack to normalize yml for diffing
#
require 'yaml'

class Hash
  # Replacing the to_yaml function so it'll serialize hashes sorted (by their keys)
  #
  # Original function is in /usr/lib/ruby/1.8/yaml/rubytypes.rb
  def to_yaml( opts = {} )
    YAML::quick_emit( object_id, opts ) do |out|
      out.map( taguri, to_yaml_style ) do |map|
        sort.each do |k, v|   # <-- here's my addition (the 'sort')
          map.add( k, v )
        end
      end
    end
  end
end


y = YAML::load_file(ARGV[0])
y = y[ARGV[1]] unless ARGV[1].nil?
puts y.to_yaml

