#!/bin/sh

# https://www.archlinux.org/mirrorlist/
curl -L -s 'https://www.archlinux.org/mirrorlist/?country=CA&country=US&protocol=https&use_mirror_status=on' | \
    sed -e 's/^#Server/Server/' -e '/^#/d' | \
    rankmirrors -n 5 -

echo "## Run ### pacman -Syyu"
