#!/bin/bash

set -e
#set -x

REPO="$1"

[ -f "$REPO/.git/config" ] || { echo "Usage: $0 ghrepo" ; exit 1; }

REPO1=$(grep 'url.*git@github.com' "$REPO/.git/config" | sed -e 's/^.*://' -e 's/\.git$//' -e 's/\//-/g')

mv -v "$REPO" "$REPO1"
