#!/bin/bash
# Removes old revisions of snaps
set -eu

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Please use sudo." >&2
    exit 1
fi

snap list --all | awk '/disabled/{print $1, $3}' | while read -r snapname revision; do
    snap remove "$snapname" --revision="$revision"
done

rm -rf /var/lib/snapd/cache/*
