#!/bin/sh

spot_service() {
        systemctl --user $1 --now spotifyd.service
}

case "$1" in
    on)
        spot_service enable
        ;;

    off)
        spot_service disable
        ;;
    *)
        echo boo
        ;;
esac
