#!/bin/sh

# https://www.cyberciti.biz/faq/linux-which-process-is-using-swap/

## Get swap space in Linux using bash for loop ##
for file in /proc/*/status ; do
  awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file;
done | sort -k 2 -n -r
