#!/bin/bash

sudo pacman -Syu --noconfirm
sudo pacman -Sc --noconfirm

nix-update

rustup update
cargo install-update -a

UpDoom

sudo btrfs filesystem defragment -r /
sudo btrfs filesystem defragment -r /nix
sudo fstrim --verbose --all
