#!/bin/bash

set -x

[ "$(id -u)" == "0" ] || { echo "You must be root" ; exit 1; }

function dfr() {
    btrfs filesystem defragment -r "$@"
}

dfr -czstd /
dfr        /home
dfr -czstd /nix
dfr        /var

for d in $(btrfs subvolume list / | grep -E 'path (home|var)/' | sed -e 's/^.* path //') ; do
    dfr "/$d"
done

fstrim --verbose --all
